{{- range $i, $domain := .Values.domains }}
{{- $domainName := ($domain.name | required ".Values.domains.name requires a valid domain" | trimPrefix "https://" | trimPrefix "http://" | trimSuffix "/") -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Values.application.name | default "app" }}-{{ $domainName | replace "." "-" }}-http-vs
  namespace: {{ $.Release.Namespace }}
  labels:
    organization: {{ $.Values.organization | default "thegangtechnology" }}
    application.name: {{ $.Values.application.name | default "app" | quote }}
    application.env: {{ $.Values.application.environment | default "dev" | quote }}
    domain.name: {{ $domainName }}
spec:
  hosts:
    - {{ $domainName }}
    {{- if $domain.wildcard }}
    - "*.{{ $domainName }}"
    {{- end }}
  gateways:
    - {{ $.Values.gateway.namespace | default "istio-gateway" }}/{{ $.Values.gateway.name | default "istio-gateway" }}
  http:
  {{- range $ii, $httpService := $domain.httpServices }}
    - match:
    {{- range $httpService.matchers }}
      - {{ . | toYaml | nindent 8 | trim }}
    {{- end }}
      route:
        - destination:
            host: {{ $httpService.route.name | quote }}
            port:
              number: {{ $httpService.route.port }}
      headers:
        response:
          set:
            Strict-Transport-Security: "max-age={{ $.Values.gateway.hstsMaxAge | default "86400" }};"
            {{- if and (hasKey $httpService "additionalResponseHeaders") ($httpService.additionalResponseHeaders) -}}
              {{- toYaml $httpService.additionalResponseHeaders | nindent 12 }}
            {{- end }}
      {{- if and (hasKey $httpService "corsPolicy") ($httpService.corsPolicy) }}
      corsPolicy:
        {{- if and (hasKey $httpService.corsPolicy "origins") ($httpService.corsPolicy.origins) }}
        allowOrigins:
        {{- range $httpService.corsPolicy.origins }}
          - exact: {{ . | quote }}
        {{- end }}
        {{- end }}
        allowCredentials: {{ $httpService.corsPolicy.allowCredentials | default "false" }}
        allowHeaders:
          {{- range $httpService.corsPolicy.allowHeaders }}
          - {{ . | quote }}
          {{- end }}
      {{- end }}
  {{- end }}
---
{{- end }}