{{- if and .Values.gateway.enabled .Values.gateway.exposeServices.enabled -}}
{{- range $i, $domain := .Values.domains }}
{{- $domainName := ($domain.name | required ".Values.domains.name requires a valid domain" | trimPrefix "https://" | trimPrefix "http://" | trimSuffix "/") -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Values.application.name | default "app" }}-{{ $domainName | replace "." "-" }}-tcp-vs
  namespace: {{ $.Release.Namespace }}
  labels:
    organization: {{ $.Values.organization | default "thegangtechnology" }}
    application.name: {{ $.Values.application.name | default "app" | quote }}
    application.env: {{ $.Values.application.environment | default "dev" | quote }}
    domain.name: {{ $domainName }}
spec:
  hosts:
    - {{ $domainName }}
    {{- if $domain.wildcard }}
    - "*.{{ $domainName }}"
    {{- end }}
  gateways:
    - {{ $.Values.gateway.namespace | default "istio-gateway" }}/{{ $.Values.gateway.name | default "istio-gateway" }}
  tcp:
    {{- range $ii, $service := $domain.tcpServices }}
    - match:
      - port: {{ $service.port }}
      {{- range $service.matchPorts }}
      - port: {{ . }}
      {{- end }}
      route:
        - destination:
            host: {{ $service.name | quote }}
            port:
              number: {{ $service.port }}
    {{- end }}
---
{{- end }}
{{- end }}